- name: install nginx
  apt: name=nginx state=installed

- name: remove default config
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: add logs.conf and olddomains.conf
  copy: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item }}
  with_items: [ "logs.conf", "olddomains.conf" ]
