---
- hosts: all
  gather_facts: no
  tasks:
    - name: fix rights
      file: dest={{ item }} owner=www-data group=www-data recurse=yes
      with_items: 
        - /var/www/geekparty
        - /var/www/geekpartysu

    - name: update composer deps
      shell: /usr/bin/composer install chdir={{item}}
      sudo: true
      sudo_user: www-data
      with_items: 
        - /var/www/geekparty
        - /var/www/geekpartysu

    - name: clear app cache
      shell: app/console --env={{item[0]}} c:c chdir=/var/www/{{item[1]}}
      sudo: true
      sudo_user: www-data
      with_nested: 
          - [ prod, dev ]
          - [ geekparty, geekpartysu ]

    - name: restart services
      service: name={{ item }} state=restarted
      with_items: [ nginx, php5-fpm ]
