#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: no
  roles: 
    - role: mysql
      tags: [ mysql ]

    - role: site
      code_dir: /var/www/gamedevparty.ru
      branch: master
      mysql_db: geekparty
      domain: gamedevparty.ru
      fb_app_id: "{{ master.fb_app_id }}"
      fb_secret: "{{ master.fb_secret }}"
      admin_email: "{{ master.admin_email }}"
      vk_app_id: "{{ master.vk_app_id }}"
      vk_app_secret: "{{ master.vk_app_secret }}"
      tags: [ site, gamedevparty ]

    - role: site
      code_dir: /var/www/geekparty.su
      branch: develop
      mysql_db: geekpartysu
      domain: geekparty.su
      fb_app_id: "{{ develop.fb_app_id }}"
      fb_secret: "{{ develop.fb_secret }}"
      admin_email: "{{ develop.admin_email }}"
      vk_app_id: "{{ develop.vk_app_id }}"
      vk_app_secret: "{{ develop.vk_app_secret }}"
      tags: [ site, geekpartysu ]

    - role: backup
      tags: [ backup ]

    - role: keereal
      tags: [ keereal ]

    - role: iptables
      tags: [ iptables ]

    - role: gohub
      tags: [ gohub ]

  tasks:
    - name: ensure server software installed
      apt: name={{ item }} state=installed
      with_items: [ nginx, php5-cli, php5-fpm, php5-curl, php5-mysql, git, python-mysqldb, phpmyadmin ]

    # nginx
    - name: remove default nginx config
      file: dest=/etc/nginx/sites-enabled/default state=absent

    - name: install nginx configs
      copy: src=etc/nginx/{{ item  }}.conf dest=/etc/nginx/{{ item }}.conf
      with_items: 
          - geekparty_common
          - sites-enabled/geekparty
          - sites-enabled/geekpartysu
          - sites-enabled/logs
          - sites-enabled/phpmyadmin

    # phpmyadmin
    - name: install phpmyadmin config
      copy: src={{ item }} dest=/etc/phpmyadmin/{{ item }}
      with_items: 
          - config.inc.php
          - config-db.php
