- name: install apt packages
  apt: name={{ item }} state=installed
  with_items: [ python-dateutil ]

- name: clone s3cmd from git
  git: repo=git@github.com:s3tools/s3cmd.git dest=/usr/s3cmd version=v1.5.2

- name: link s3cmd bin
  file: path=/usr/bin/s3cmd src=/usr/s3cmd/s3cmd state=link

- name: install s3cmd config file
  template: src=s3cfg dest=/root/.s3cfg

- name: install cron uploading files to s3
  cron: hour=0 minute=5 name="upload projects to s3" job="s3cmd sync {{ backup_dir }}/ s3://geekparty/"
