mysql-abstract:
    image: mysql
    external_links:
        - db
    command: bash -c "mysql -h$DB_PORT_3306_TCP_ADDR -P$DB_PORT_3306_TCP_PORT -uroot -p$DB_ENV_MYSQL_ROOT_PASSWORD"

mysql-shell:
    extens: mysql-abstract

mysql-dump:
    extends: mysql-abstract
    volumes:
        - ./:/var/data
    command: bash -c "mysqldump -h$DB_PORT_3306_TCP_ADDR -P$DB_PORT_3306_TCP_PORT -uroot -p$DB_ENV_MYSQL_ROOT_PASSWORD > /var/data/dump.sql"