mysql-abstract:
    image: mysql

mysql-shell:
    extends:
        service: mysql-abstract
    external_links:
        - docker_db_1
    command: bash -c "mysql -h$$DOCKER_DB_1_PORT_3306_TCP_ADDR -P$$DOCKER_DB_1_PORT_3306_TCP_PORT -uroot -p$$DOCKER_DB_1_ENV_MYSQL_ROOT_PASSWORD"

mysql-dump:
    extends:
        service: mysql-abstract
    volumes:
        - ./:/var/data
    external_links:
        - docker_db_1
    command: bash -c "mysqldump -h$$DOCKER_DB_1_PORT_3306_TCP_ADDR -P$$DOCKER_DB_1_PORT_3306_TCP_PORT -uroot -p$$DOCKER_DB_1_ENV_MYSQL_ROOT_PASSWORD > /var/data/dump.sql"

init:
    build: php
    external_links:
        - docker_db_1
    volumes:
        - ./data:/var/data
    working_dir: /var/data
    command: bash init.sh