app:
    image: busybox
    entrypoint: /bin/sh
    volumes:
        - ./data:/var/data
    tty: true

db:
    image: mysql
    expose:
        - 3306
    env_file:
        - vars.env

php:
    build: php
    expose:
        - 9000
    volumes_from:
        - app
    links:
        - db
    env_file:
        - vars.env

nginx:
    image: nginx
    ports:
        - 80
    links:
        - php
    volumes:
        - ./data:/var/data
        - ./data/gamedevparty.conf:/etc/nginx/conf.d/default.conf
    environment:
        VIRTUAL_HOST: gamedevparty.docker

gohub:
    build: gohub
    volumes:
        - ./data:/var/data
        - ./data/composer-cache:/root/.composer
        - ./data/gohub.json:/etc/gohub.json
        - ./data/deploy.sh:/usr/bin/deploy.sh
    ports:
        - 7654
    links:
        - db
    environment:
        VIRTUAL_HOST: gohub.docker
    env_file:
        - vars.env

templater:
    image: busybox
    links:
        - db
    volumes:
        - ./data:/var/data
    command: sh /var/data/tpl.sh
    env_file:
        - vars.env