app:
    image: busybox
    entrypoint: /bin/sh
    volumes:
        - ./data:/var/data
        - ./data/nginx-sites/gamedevparty.conf:/etc/nginx/sites-enabled/gamedevparty.conf
    tty: true
db:
    image: mysql
    expose:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret

php:
    build: php
    expose:
        - 9000:9000
    volumes_from:
        - app
    links:
        - db
        - app
nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

gohub:
    build: gohub
    volumes:
        - ./data:/var/data
    ports:
        - 7654
    environment:
        VIRTUAL_HOST: gohub.docker