# - name: fix rights
#   file: dest={{ code_dir }}/current owner=www-data group=www-data recurse=yes

# - name: update composer deps
#   shell: /usr/bin/composer install -o
#   args:
#     chdir: "{{ code_dir }}/current"
#   sudo: true
#   sudo_user: www-data

- name: clear app cache
  shell: app/console --env={{ item }} c:c 
  args:
    chdir: "{{ code_dir }}/current"
  with_items: 
    - [ prod, dev ]

# - name: restart services
#   service: name={{ item }} state=restarted
#   with_items: [ nginx, php5-fpm ]

