- name: install mysql
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items: [ mysql-server, mysql-client, python-pip, python-mysqldb ]

- name: copy mysql config
  copy: src=my.cnf dest=/etc/mysql/my.cnf

- name: copy mysql init root password file
  template: src=mysql-init dest=/tmp/mysql-init owner=mysql group=mysql

- name: stop mysql
  service: name=mysql state=stopped

- name: reset mysql password
  become: yes
  become_user: mysql
  shell: /usr/bin/mysqld_safe --init-file=/tmp/mysql-init &

- name: wait for mysql to start
  wait_for: path=/var/run/mysqld/mysqld.pid

- name: stop mysqld_safe
  shell: kill `cat /var/run/mysqld/mysqld.pid`

- name: remove mysql-init
  file: path=/tmp/mysql-init state=absent

- name: ensure mysql started
  service: name=mysql state=started

- name: ensure mysql user exists
  mysql_user: name={{ mysql_db_name }} password={{ mysql_db_password }} state=present login_user=root login_password={{ mysql_root_password }} priv=*.*:ALL

- name: ensure mysql DB exists
  mysql_db: name={{ mysql_db_name }} state=present login_user=root login_password={{ mysql_root_password }}

  # backup
- name: make backups dir writeable
  file: dest={{ backup_dir }} state=directory mode=0700

- name: copy mysql dump script
  template: src=mysql_dump.sh dest=/usr/bin/mysql_dump.sh mode=0700

- name: install mysql dump cron
  cron: hour=0 minute=0 name="geekparty mysql db dump" state=present job="/usr/bin/mysql_dump.sh"
