parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: {{ mysql_db }}
    database_user: {{ mysql_db_user }}
    database_password: {{ mysql_db_password }}
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a9bdc1fa017cc448df70cef2357e22d7782b87ca
    database_path: null
    fb_app_id: 452612894814235
    fb_secret: 63301f66bf97c5de5766cbbbbc8eaa34
    branch: {{ branch }}
    vk_app_id: 3561840
    vk_app_secret: g71CdozgcG6vZudTzLcN
    disqus_shortname: geekparty
